language: java
dist: bionic
jdk:
  - oraclejdk11
before_install:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - sudo apt-get update
  - sudo apt-get -y install argon2
# W/A for Travis CI to avoid some weird install steps
install:
  - true
before_script:
  - nvm install v13.2.0
  - npm i npm@6.13.1 -g
  - npm i eslint@v6.7.2 -g
script:
  - rake check
  - rake test
after_script:
  - JACOCO_SOURCE_PATH=$(pwd)/api/src/main/java ./cc-test-reporter format-coverage -t jacoco api/build/reports/jacoco/test/jacocoTestReport.xml
  - ./cc-test-reporter upload-coverage -r $CC_TEST_REPORTER_ID
