language: java
dist: trusty
jdk:
  - oraclejdk8
# W/A for Travis CI to avoid some weird install steps
install:
  - true
before_script:
  - npm i npm@latest -g
  - npm i eslint -g
script:
  - rake check
  - rake test