language: java
dist: trusty
jdk:
  - oraclejdk8
# W/A for Travis CI to avoid some weird install steps
install:
  - true
before_script:
  - nvm install v13.2.0
  - npm i npm@6.13.1 -g
  - npm i eslint@v6.7.2 -g
script:
  - rake check
  - rake test