def gradle(*args)
  trap('SIGINT') { exit }
  sh "./gradlew", *args
end

task :bootstrap do
end

desc "check the code"
task :check => :bootstrap do
  gradle "verGJF"
end

desc "fix the code"
task :fix => :bootstrap do
  gradle "goGJF"
end

desc "test the code"
task :test => :bootstrap do
  gradle "cleanTest", "test", "jacocoTestReport"
end

desc "run development version"
task :run_dev => :check do
  gradle "bootRun", "--args='--spring.config.location=file:./config/configuration.yaml'"
end

desc "build production version"
task :build_prod, [:output] => :check do |_, args|
  gradle "bootJar"
  if args.output
    FileUtils.mkdir_p args.output
    version = File.open("version").read.strip
    FileUtils.cp "build/libs/chezz-#{version}.jar", args.output
  end
end